name: SonarQube Analysis
on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Build and test with Maven
        run: mvn clean verify -DskipTests
      
      - name: Set up SonarScanner
        run: |
          sudo apt-get install -y unzip
          wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-5.0.1.3006-linux.zip
          unzip -q sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH
      
      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=ERP-Back-End \
            -Dsonar.projectName="ERP-Back-End" \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=src \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.exclusions=**/*.test.java,**/*.spec.java,**/test/**,**/target/** \
            -Dsonar.language=java \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.verbose=true
